### ISSUE TITLE
html2pdf NPM package not rendering html styles correctly

### ISSUE THREAD

**Issue by airarrazaval** [eKoopmans/html2pdf.js#101]
Using html2pdf from npm repo will render PDF without correct styles (borders and others). 

Changing

`"html2canvas": "https://github.com/eKoopmans/html2canvas/tarball/develop"`

to

`"html2canvas": "^1.0.0-alpha.11"`

in the dependencies of html2pdf.js package.json fixed the problem (don't know if it breaks something else)

**Comment by eKoopmans** [comment]
Thanks, this was corrected in 5c629ec. Closing.
