### ISSUE TITLE
PDF does not show images

### ISSUE THREAD

**Issue by alicankahramaner** [eKoopmans/html2pdf.js#105]
Hi,

I am use vuejs.

This is usage for the my vue method.

> html2pdf(reportContent, {
                margin: [5, 5, 11, 5],
                filename: `${this.data.infoCard.reportType}-${this.data.infoCard.reportTitle}-${this.dateRange}.pdf`,
                html2canvas: {
                    dpi: 300,
                    letterRendering: true
                },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
            });

Please help.

@eKoopmans

**Comment by guttenberger** [comment]
try with this html2canvas config:

> html2canvas {
>     dpi: 300,
>     letterRendering: true,
>     useCORS: true
> }

useCORS tries to load images from a server with CORS.

**Comment by mufaddalmw** [comment]
Ran into same issue, I made changes in below line of code-
`image: { type: "jpg", quality: 0.95 },`
so instead of `jpeg` change it to `jpg`, seems to be working but facing another issue with file size, its quite heavy.

**Comment by madhu-b** [comment]
I'm using same code as below but images for not loading from external URL.

 ` var element = document.getElementById('print');
          html2pdf(element, {
            margin: 1,
            filename: $rootScope.globalSelectedEvent.code + '_userCard.pdf',
            image: {type: 'jpg', quality: 0.99},
            html2canvas: {dpi: 192, letterRendering: true},
            jsPDF: {unit: 'pt', format: 'letter', orientation: 'portrait'}
          });`

i tried using useCORES:true for html2canvas but it failed. Please advice.

I'm also facing file size issue of it crosses some 20pages.

**Comment by PhilipTKC** [comment]
Not the best solution, But if possible convert your images to Base64.

**Comment by sameerpallav** [comment]
jpg is not supported for html2canvas. Read the docs. 
The image type. HTMLCanvasElement only supports 'png', 'jpeg', and 'webp' (on Chrome).

**Comment by alicankahramaner** [comment]
@sameerpallav thank you

**Comment by schandra-rpx** [comment]
can anyone kindly help me to understand what is wrong with the https://jsfiddle.net/zkypa0uo/2/

I'm not getting image in the PDF.

**Comment by alicankahramaner** [comment]
Try png file format

https://jsfiddle.net/tjdvoq3e/

**Comment by rkorchid** [comment]
i have the same problem, i tried the last exemple but not working.

**Comment by YaroslavKozhemiaka** [comment]
> i have the same problem, i tried the last exemple but not working.

Use base64 into img src

**Comment by christiansaavedra** [comment]
Three things got me fixing this:

1) Allow CORS in your server. In my case I use AWS S3, so I went to configuration and there you have the instruction to activate it

2) Add a "crossorigin" attribute with a "*" value to your img html tags. I used javascript for this:

let imagenes = document.getElementsByTagName("img");
    for (let i = 0; i < imagenes.length; i++) {
      imagenes[i].setAttribute("crossorigin", "*");

3) Adding useCORS: true as an html2canvas option

**Comment by pSnehanshu** [comment]
Thanks @guttenberger, your solution worked.

**Comment by aminikhil** [comment]
If you are using firebase then check this solution, https://stackoverflow.com/questions/37760695/firebase-storage-and-access-control-allow-origin

**Comment by garavito16** [comment]
thanks @guttenberger, your solution helped me a lot.

**Comment by LasithEranga** [comment]
> try with this html2canvas config:
> 
> > html2canvas {
> > dpi: 300,
> > letterRendering: true,
> > useCORS: true
> > }
> 
> useCORS tries to load images from a server with CORS.

thanks, it worked.
I put the following code in the .htaccess file in my server as well
`<IfModule mod_headers.c>`</br>
    `Header set Access-Control-Allow-Origin "*"`</br>
`</IfModule>`

**Comment by ajukhullar** [comment]
Try this code , It will work 


      exportToPDF() {
            html2pdf(document.getElementById("element-to-convert"), {
                margin: 1,
                filename: "i-was-html.pdf",
                html2canvas: {
                    useCORS: true,
                },
            });
        },

**Comment by AhmedMuhammedElsaid** [comment]
I had the same issue and the following configs work with me just fine 
`          // @ts-ignore
          import("html2pdf.js").then(html2pdf => {
            html2pdf
              .default()
              .from(wrapper)
              .set({
                filename: "analytics.pdf",
                html2canvas: {
                  dpi: 300,
                  letterRendering: true,
                  useCORS: true,
                  scale: 2,
                },
                jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
                pagebreak: { mode: "avoid-all", before: "#page2el" },
                image: { type: "jpeg", quality: 1 },
              })
              .save()`

**Comment by indranilm2023** [comment]
in my case, the image is being dynamically rendered. For example, a page where the logo image url (azure blob) gets rendered from server. Can anybody help in my case. Tech stack is ReactJS and I am using https://www.npmjs.com/package/html2pdf.js/v/0.10.1

**Comment by xbabek02** [comment]
I solved this issue by replacing svg image that was not rendering with the png variant.

**Comment by EvansRobbie** [comment]
> I solved this issue by replacing svg image that was not rendering with the png variant.

This is it mate, You literally saved my life. Thank you
