### ISSUE TITLE
When scrolling the div that is used for printing, there is a margin or an empty page added to the PDF.

### ISSUE THREAD

**Issue by DavGer** [eKoopmans/html2pdf.js#175]
Using V0.9.1.
So I have one big div with multiple other div's inside this div.
The export goes fine when I don't scroll on the page.
When I scroll so the top elements are not visible anymore the first half of the first page of the export is blank.
When I scroll even further the first page is completely blank and everything is shifted downwards.
The code I use for exporting is:
`
var element = document.getElementById('export-div');

        var options = {
          margin: 1,
          filename: 'file.pdf',
          html2canvas: {
            scale: 4,
            y: -70
          },
          jsPDF: {
            unit: 'cm',
            format: 'a4',
            orientation: 'landscape'
          }
        };

        html2pdf().set(options).from(element).save();`

Is this a bug or am I doing something wrong?

**Comment by DavGer** [comment]
[I forked the fiddle](https://jsfiddle.net/9otkrhsw/).
So if you just click the button you will see that the export is okay.
When you then scroll so that only the button is visible you can see that the export has white space on the top of the page, similar to the amount that was scrolled.
That `y: -70` was a typo btw.

When I first forked the fiddle it did not show this behavior. It was only after I added the options that this happened. So the bug should be in there somewhere.

**Comment by eKoopmans** [comment]
Hi @DavGer, the issue is in your use of `y: 0` (or any explicit value for `y`). If you leave it unset, html2canvas should automatically determine the correct y value for the element. Is there a reason you need to set `y` explicitly?

**Comment by DavGer** [comment]
That does the trick! No I don't need to set it, not sure why I did in the first place.
As far as I'm concerned you can close this issue. Thanks for the help!

**Comment by trptcolin** [comment]
Wanted to share an update for anybody else who runs into similar issues - we added `scrollX: 0, scrollY: 0` to the html2canvas options to get past this ([html2canvas docs](http://html2canvas.hertzen.com/configuration/)).

Without it, the symptom for us was that a button at the top of the page worked great to generate a PDF. But the same exact button, further down on the page (calling the same PDF-generating function) was inserting a bunch of blank pages in the output PDF. And eventually we happened to notice in the debugger (paused when the `html2pdf__overlay` stuff gets added) this issue didn't happen if we scrolled to the top of the page. 

Might be something that's worth either calling out explicitly in the example html2canvas options in the README, or even perhaps providing by default.

**Comment by AmericanAvalanche** [comment]
@trptcolin's scrollX: 0, scrollY: 0 solution fixed the same issue for me, thanks!

**Comment by rovercarlosb** [comment]
@trptcolin Thanks, options scrollX:0, scrollY:0 solution fixed the same issue!

**Comment by alexey-yakovlev** [comment]
@trptcolin Thanks!

**Comment by TheMuyu** [comment]
> @trptcolin Thanks, options scrollX:0, scrollY:0 solution fixed the same issue!

Hello I have same problem how can I add that scrollX and scrollY into my code? I'm using html2canvas in angular

```
  public SavePDF(): void {
    const DATA = document.getElementById('frontpage');

    html2canvas(DATA).then(canvas => {
      const fileWidth = 224;
      const fileHeight = canvas.height * fileWidth / canvas.width;
      console.log(fileHeight);
      const FILEURI = canvas.toDataURL('image/png')
      const PDF = new jsPDF(
        {
          orientation: 'portrait',
          unit: 'px',
          format: [fileWidth + 10, fileHeight + 10]
        }
      );
      const position = 0;
      PDF.addImage(FILEURI, 'PNG', 0, 0, fileWidth, fileHeight, 'FRONT', 'NONE');

      PDF.save('demo.pdf');
    });
  }
```

**Comment by raoasifraza11** [comment]
> Wanted to share an update for anybody else who runs into similar issues - we added `scrollX: 0, scrollY: 0` to the html2canvas options to get past this ([html2canvas docs](http://html2canvas.hertzen.com/configuration/)).
> 
> Without it, the symptom for us was that a button at the top of the page worked great to generate a PDF. But the same exact button, further down on the page (calling the same PDF-generating function) was inserting a bunch of blank pages in the output PDF. And eventually we happened to notice in the debugger (paused when the `html2pdf__overlay` stuff gets added) this issue didn't happen if we scrolled to the top of the page.
> 
> Might be something that's worth either calling out explicitly in the example html2canvas options in the README, or even perhaps providing by default.

> working fine

**Comment by abhishekcpwebline** [comment]
@TheMuyu  - Have you got the solution for angular ?

**Comment by peapaa** [comment]
When I generate a PDF using html2canvas and jsPDF, the div with className="overflow-auto h-[200px]" only shows the first 
page with data when printing, while pages 2 and 3 are blank. Please provide me with a solution.

const handleDownloadPdf = async () => {
    const element = printRef.current;
    const options = {
      allowTaint: true,
      dpi: 300,
      letterRendering: true,
      logging: false,
      scale: 1,
    };
    if (element) {
      console.log("scrollTop", element.scrollTop);
      const currentPosition = element.scrollTop;
      element.style.height = "auto";
      const totalHeight = element.scrollHeight; // Chiều cao tổng của phần tử
      console.log("totalHeight", totalHeight);
      const pdf = new jsPDF("p", "px", "a4");
      const marginLeft = 20 * 3.77953; // Lề trái
      const marginTop = 20 * 3.77953; // Lề trên

      const pdfWidth = 210 * 3.77953; // Chiều rộng A4
      const pdfHeight = 297 * 3.77953; // Chiều cao A4

      const imgWidth = pdfWidth - marginLeft * 2; // Chiều rộng hình ảnh
      console.log("imgWidth", imgWidth);

      let remainingHeight = totalHeight; // Chiều cao còn lại cần chụp
      let positionY = 0; // Tọa độ Y ban đầu cho phần nội dung

      // Chụp từng phần nội dung
      while (remainingHeight > 0) {
        // Xác định chiều cao tối đa cho mỗi trang
        const canvasSectionHeight = Math.min(
          remainingHeight,
          pdfHeight - marginTop * 2 // Chiều cao tối đa cho mỗi trang
        );
        console.log("remainingHeight", remainingHeight);
        console.log("canvasSectionHeight", canvasSectionHeight);

        element.scrollTop = positionY;
        console.log("element.scrollTop", element.scrollTop);
        console.log("positionY", positionY);
        // Chụp hình phần nội dung
        await new Promise((resolve) => setTimeout(resolve, 500));
        const canvas = await html2canvas(element, {
          ...options,
          height: canvasSectionHeight,
          y: positionY,
        });
        const imgData = canvas.toDataURL("image/png");
        const imgHeight = (canvas.height * imgWidth) / canvas.width; // Tính chiều cao hình ảnh
        console.log("imgHeight", imgHeight);
        // Thêm hình ảnh vào PDF
        pdf.addImage(
          imgData,
          "PNG",
          marginLeft,
          positionY,
          imgWidth,
          imgHeight,
          undefined,
          "FAST"
        );

        // Cập nhật các biến cho lần chụp tiếp theo
        remainingHeight -= canvasSectionHeight;
        positionY += canvasSectionHeight;

        if (remainingHeight > 0) {
          pdf.addPage(); // Thêm trang mới nếu còn nội dung
        } else {
          pdf.save("web.pdf"); // Lưu PDF khi hoàn tất
        }
      }
      element.style.height = "200px";
      element.scrollTop = currentPosition;
    } else {
      console.error("Element not found for PDF generation.");
    }
  };
