### ISSUE TITLE
Issue while exporting multi page pdf which has multiple highcharts in IE 11

### ISSUE THREAD

**Issue by hemantkabra** [eKoopmans/html2pdf.js#193]
Hi @eKoopmans Thank you for building such a nice library. I really loved it but currently I am facing an issue while exporting a big pdf file in IE 11 which has 15 pages and also contains multiple highcharts (around 9-10). Couple of pages in the starting of PDF are exporting correctly but after that it exports only blank pages.

I found that it is because of the canvas's limitation in IE so as a try I exported three different PDF file which is working fine. But I don't want to go with this solution so Is there anything else in html2pdf which can help me to split the large canvas and then export it in a single pdf file only?

Any suggestion/help is highly appreciated on this.

**Comment by eKoopmans** [comment]
Hi @hemantkabra, yes, take a look [here](https://github.com/eKoopmans/html2pdf/issues/19#issuecomment-455868274). It still requires splitting it into smaller pieces, but you should be able to combine those pieces into a single PDF using the code I linked.

Other than that, there's no other solution currently. You can follow #19 for further developments though!

**Comment by hemantkabra** [comment]
Hi @eKoopmans , Thank you for the details. This one really worked for me. Thanks a lot once again for the help and support.

**Comment by eKoopmans** [comment]
Great, glad it worked! I'll close, anyone else looking here follow #19 for the latest info.
