### ISSUE TITLE
Image in canvas leads to error

### ISSUE THREAD

**Issue by RRaideRR** [eKoopmans/html2pdf.js#194]
Hey guys,

see this jsfiddle: https://jsfiddle.net/cj3vxsbq/2/

I want to export the div to a PDF document. The div has an image as you can see. However, with the parameter allowTaint: false, only "Hello World" is saved to the PDF. With allowTaint: true, nothing happens and I can see in the console the error "The operation is insecure."

Does anyone has an idea what I'm doing wrong?

**Comment by eKoopmans** [comment]
Hi @RRaideRR, yes this is an unavoidable part of how files on the Internet work. Generally, remote images can't be rendered onto a canvas without "tainting" it - and once it's tainted, you can't read from it. So `allowTaint` will never work.

`useCORS` tries to get around that issue, but only works if the remote source has a CORS policy set up (an "Access-Control-Allow-Origin" header). Failing that, your only option is to use a proxy. See the [html2canvas docs](http://html2canvas.hertzen.com/configuration) for more info on that.

Related issue: #189.

**Comment by NikhilGangurde** [comment]
i tried all option still not working!!

**Comment by Pan-Rong** [comment]
Hi, I have the same issue, can you tell me how to solve it?

**Comment by RRaideRR** [comment]
As @eKoopmans told: the remote source has to set up a corresponding CORS policy. Then you just can go with: `html2canvas:  {useCORS:true }`

**Comment by Pan-Rong** [comment]
> As @eKoopmans said: the remote source has to set up a corresponding CORS policy. Then you just can go with: `html2canvas: {useCORS:true }`

thank you~
