### ISSUE TITLE
Missing bundle file

### ISSUE THREAD

**Issue by boroth** [eKoopmans/html2pdf.js#202]
I just tried installing through npm/yarn, and the only files in the dist directory are the include and require directories, and the html2pdf.js file. No minified files, no bundled files. Do I have to run these through Webpack on my own to get the bundle?

**Comment by eKoopmans** [comment]
Hi, the bundles are deliberately left out of the NPM dist. Otherwise they would add considerably to the file size for any package using html2pdf.js as a dependency.

You can run `npm run build` to fully rebuild the `dist` directory.

**Comment by boroth** [comment]
Perfect, thanks!
