### ISSUE TITLE
is there any way to skip the prompt for save?

### ISSUE THREAD

**Issue by mobilelinux** [eKoopmans/html2pdf.js#207]
After call
html2pdf().from(element).set({
 margin: 0,
 filename: 'report' + '.pdf',
...
}).save();
the file will be saved directly with name as report.pdf.

Is there any way to achieve that? thanks

**Comment by eKoopmans** [comment]
Hi, you mean without asking where to save the file? I believe that would just depend on browser settings, not something we could control.

**Comment by mobilelinux** [comment]
Yes. 
Actually when we download something from a webpage it will  always be downloaded directly in download directory, right? 
whether save() can be implemented like that? directly saved to download directory without requiring user to do a click.

**Comment by eKoopmans** [comment]
As mentioned, this is browser-dependant and not in our control. For instance, if you try `.save()` with Chrome and disable the setting "Ask where to save each file before downloading", it will automatically download with no prompt. There is no way to bypass this (and there *shouldn't be*) - users have control over how their browsers interact with files.

Closing.

**Comment by mobilelinux** [comment]
yes you are right. thank you very much for your help.
