### ISSUE TITLE
NPM Install not working?

### ISSUE THREAD

**Issue by oselly** [eKoopmans/html2pdf.js#223]
Hello,

I'm having a bit of an issue with the npm install (previously has worked fine) but when i'm trying to run the npm install html2pdf.js command it's hanging on
"fetchMetadata: sill resolveWithNewModule base64-arraybuffer@0.1.5 checking installable status" and not resolving itself.

I can install other npm packages without issue, (my proxy is configured) and I can install the base64-arraybuffer via npm without issue as well. Is there something going on behind the scenes or is it just my setup somehow?

**Comment by eKoopmans** [comment]
Hi @oselly, what was the solution?

**Comment by oselly** [comment]
I'm still investigating but it does seem to appear like it's an internal issue, checking out the npm debug log it's failing on 

git ls-remote -h -t https://github.com/eligrey/FileSaver.js.git

**Comment by oselly** [comment]
https://github.com/MrRio/jsPDF/issues/2437

**Comment by oselly** [comment]
If I manually install jspdf v1.5.2 then I can install html2pdf.js without problem

**Comment by eKoopmans** [comment]
Okay thanks @oselly, sounds like there may be some issues with the latest jsPDF.
