### ISSUE TITLE
how to have the image of logo on the pdf  but not on the html page?

### ISSUE THREAD

**Issue by tekboy123-2019** [eKoopmans/html2pdf.js#236]
is there a way to add  an image  on the pdf  only but not on the html page?
i want to have a small logo to  on the pdf page only

**Comment by bendeca** [comment]
see issue #229

```javascript
html2pdf().from(element).set(opt).toPdf().get('pdf').then(function (pdf) {
var totalPages = pdf.internal.getNumberOfPages();

for (i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.addImage(image, "PNG", 0, 0, 200, 200);
}
}).save();
```

You can get the jsPDF Object and alter it with jsPDF functions, see documentation here:
[jsPDF addImage](https://rawgit.com/MrRio/jsPDF/master/docs/module-addImage.html)

**Comment by tekboy123-2019** [comment]
im trying to add the image to the pdf, first i got this error

> Error: addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added. html2pdf.bundle.min.js:2518:199

after refresh the page the error is gone and i can click on the button to create pdf but it will  create a blank pdf, can anyone tell me what im doing wrong


`<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Untitled Document</title>
</head>

<body>
<style>
body{color: #000; font-family: "Helvetica Neue", Helvetica, Arial, "sans-serif"; font-size: 18px}
h1{color: #117F08; font-size: 50px; font-weight: 500}
.bgred{background: red}
.img-fluid{max-width:100px; height:auto}
#element-to-print{max-width:980px; margin:0 auto}
</style>
<button id="generate">Create PDF</button>
<div id="element-to-print">
  <h1> h1 header </h1>
  <p>This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. </p>
  <p>
    <input type="checkbox">
    this is a checkbox 1 </p>
  <p>
    <input type="checkbox">
    this is a checkbox 2</p>
  
  <ul>
    <li>list </li>
    <li>list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list list <a href="#">link</a> list list list list list </li>
    <li>list </li>
    <li><a href="#">list with hyperlink</a> </li>
  </ul>
</div>
<script src="html2pdf.bundle.min.js"></script> 

<script>
document.getElementById('generate').onclick = function () {

var element = document.getElementById('element-to-print');
var opt = {
  margin:       1,
  filename:     'myfile.pdf',
  image:        { type: 'jpeg', quality: 1 },
  html2canvas:  {scale: 2},
  jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
};

html2pdf().from(element).set(opt).toPdf().get('pdf').then(function (pdf) {


var img = new Image();
img.src = ('rlogo.jpg');
pdf.addImage(img, "JPEG", 0, 0, 200, 200);

/* var totalPages = pdf.internal.getNumberOfPages();

  for (i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(10);
    pdf.setTextColor(150);
    pdf.text('Page ' + i + ' of ' + totalPages, pdf.internal.pageSize.getWidth() - 100, pdf.internal.pageSize.getHeight() - 30);
  }*/


})
.save();
	

  
};





</script>
</body>
</html>
`

**Comment by tekboy123-2019** [comment]
i changed the image to base64 image, got no error and was abled to create the pdf  but still no image on the pdf
https://jsfiddle.net/x4mrjbun/1/

**Comment by Christophe-re** [comment]
Hi, 
Check this : [https://jsfiddle.net/956y82c4/2/](https://jsfiddle.net/956y82c4/2/)
