### ISSUE TITLE
Punctuation Issue After Exporting to PDF for Unicode languages (Arabic)

### ISSUE THREAD

**Issue by AthalG** [eKoopmans/html2pdf.js#242]
The library works perfectly with the Arabic language, however, after exporting the PDF file the full stops and brackets seem to flip to be right before the word it follows.
If I try to fix it manually, the mark seems to mess up even more.

I'd like to note that I have done everything to support Arabic in CSS and it works great with HTML.

Example of how the punctuation should be:
<img width="706" alt="Screenshot 2019-07-08 at 11 45 26" src="https://user-images.githubusercontent.com/52150793/60796455-10b4ad80-a176-11e9-999f-dd7d7e7f7d6a.png">

and here's how it shows:
<img width="704" alt="Screenshot 2019-07-08 at 11 45 39" src="https://user-images.githubusercontent.com/52150793/60796487-1f02c980-a176-11e9-83be-915ed9426c22.png">

**Comment by AthalG** [comment]
I've found a solution from [here](https://www.w3.org/International/articles/inline-bidi-markup/) adding `<span dir="rtl">.</span>&rlm;` around the punctuation marks will solve the problem after exporting to PDF.

**Comment by tesla-ES** [comment]
how u get this result can u share your code with us pls
