### ISSUE TITLE
Auto print?

### ISSUE THREAD

**Issue by sridhargoshika** [eKoopmans/html2pdf.js#243]
Is there a way to print PDF without download?

**Comment by eKoopmans** [comment]
Hi @sridhargoshika, html2pdf.js uses jsPDF to create its files, so you can check how to do things like print the PDF on their resources - for instance, [MrRio/jsPDF#335](https://github.com/MrRio/jsPDF/issues/335#issuecomment-211535101).

In html2pdf.js, you can access the PDF object like so:

```js
html2pdf().from(element).toPdf().get('pdf').then(function (pdfObj) {
    // pdfObj has your jsPDF object in it, use it as you please!
    // For instance (untested):
    pdfObj.autoPrint();
    window.open(pdfObj.output('bloburl'), '_blank');
});
```

**Comment by sridhargoshika** [comment]
Thank You for quick reply.  works like a charm :-)

**Comment by Anuragck** [comment]
> Hi @sridhargoshika, html2pdf.js uses jsPDF to create its files, so you can check how to do things like print the PDF on their resources - for instance, [MrRio/jsPDF#335](https://github.com/MrRio/jsPDF/issues/335#issuecomment-211535101).
> 
> In html2pdf.js, you can access the PDF object like so:
> 
> ```js
> html2pdf().from(element).toPdf().get('pdf').then(function (pdfObj) {
>     // pdfObj has your jsPDF object in it, use it as you please!
>     // For instance (untested):
>     pdfObj.autoPrint();
>     window.open(pdfObj.output('bloburl'), '_blank');
> });
> ```

How to add custom filename for download the pdf (when using this bloburl )
