### ISSUE TITLE
Blank PDF If there are more than 5 images

### ISSUE THREAD

**Issue by mkarem4** [eKoopmans/html2pdf.js#253]
When I try to export pdf from a page which has more 5 images it generates blank pdf and when I change some options it generates black pdf
these are the options I use
var opt = {
            margin: 1,
            filename: 'Export.pdf',
            image: {type: 'jpeg', quality: 0.98},
            html2canvas: {scale: 5, imageTimeout: 10},
            jsPDF: {unit:'mm', format:'letter', orientation:'p'}
        };
        html2pdf().from(element).set(opt).save();

Notice: it works when the page contains less than 5 images, this issue appears when the page has more than 5 images

**Comment by mkarem4** [comment]
@eKoopmans any suggestions for this, please ?!

**Comment by Adil-R** [comment]
How are you suppose to close it without resolving?

**Comment by Adil-R** [comment]
@eKoopmans ?

**Comment by eKoopmans** [comment]
Hi, this is known issue 6 from this list:
https://github.com/eKoopmans/html2pdf.js#known-issues

Unfortunately, the only current solutions are to:
- reduce the size of your image (the easiest candidate is reducing the `scale` value), or
- split it into multiple PDFs

**Comment by harmeetsingh17** [comment]
@eKoopmans reducing the scale worked for me. but the thing is that I am getting my pdf file of around 250-300mb which is a lot. is there any way to optimize the pdf size?

**Comment by eKoopmans** [comment]
Haha yep that is a lot! The thing is, it's literally creating images of the content, so the complexity of those images and the image quality will have a direct impact. You could try reducing the quality of the image, e.g. switching to jpeg if you're using PNG, and reducing the quality of the jpeg.
