### ISSUE TITLE
Multipage pdf creating issue of black screen on first page.

### ISSUE THREAD

**Issue by dgolhar** [eKoopmans/html2pdf.js#259]
I am facing issue if the converted pdf is more than one page.
all pages except last page shows as page with black color background only.
My code is as follows:

               $("#elementId1").css('max-height', '300000px');
              var element = document.getElementById('elementId1');
              var clnElement = element.cloneNode(true);
              clnElement.style.width = "100%";
              clnElement.style.maxHeight = "3000px";
              clnElement.style.background = "transparent";

            var opt = {
              margin:       1,
              filename:     'myfile.pdf',
              image:        { type: 'jpeg', quality: 0.96 },
              html2canvas: {scale: 2, logging: true},
              jsPDF: {unit: 'pt', format: 'a4', orientation: 'p'},
            };
         
            html2pdf(clnElement, opt);
![Screenshot from 2019-10-16 18-47-59](https://user-images.githubusercontent.com/55698179/66922867-836ed800-f045-11e9-82f9-931af50043f7.png)

TIA!

**Comment by arlogilbert** [comment]
I'm having the same issue. If anybody finds a solution please tag me.

Here's my code.

```
  $('#cmd').click(function () {
        var element = document.getElementById('main');
        var opt = {
          filename:     'Osano-Privacy-Audit-{{ datetimeformat(unixtimestamp, "%B-%e-%Y") }}.pdf',
          jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' },
          pagebreak:    { mode: 'css' } 
        };
      html2pdf().set(opt).from(element).save().then(function(){
        $("html").removeClass( "printable" );
    });
  });
```

**Comment by sameerpallav** [comment]
same problem here. This issue started a few days ago again.

**Comment by dimitrianoudi** [comment]
I have the same issue. Anyone out there to assist?

**Comment by malyi** [comment]
Timeout helps me: 
        const pdf = Html2pdf().set(options).from(element.innerHTML).outputImg();
        pdf.then(() => {
            setTimeout(() => {
                pdf.save();
            }, 5000);
        });

**Comment by dgolhar** [comment]
Thanx @malyi . Its works!
