### ISSUE TITLE
html2pdfjs 'radio button' getting deselected in html while converting html to PDF

### ISSUE THREAD

**Issue by dgolhar** [eKoopmans/html2pdf.js#267]
I am trying convert html to PDF.
My html contains radio buttons and checkbox. 
If checkbox is selected in html then while converting to PDF checkbox and radio button is 
comes as selected which works correctly but selected radio button turns to deselected during this process. 
My AngularJS code is follows   
   
       $("#elementId1").css('max-height', '300000px');
          var element = document.getElementById('elementId1');
         var opt = {
          margin:       1,
          filename:     'myfile.pdf',
          image:        { type: 'jpeg', quality: 0.96 },
          html2canvas: {scale: 2, logging: true},
          jsPDF: {unit: 'pt', format: 'a4', orientation: 'p'},
        };
     
        const pdf = html2pdf().set(opt).from(updatedElement).outputImg();
         pdf.then(function() { 
              pdf.save();
          });

   Thanks in Advanced!

**Comment by dgolhar** [comment]
Radio button coming as deselected after 8 pages even if its selected in ui

**Comment by dgolhar** [comment]
Its solved by changing 'scale' value in html2canvas to 1.5.

**Comment by aGitForEveryone** [comment]
I am facing that issue today. What do you mean by `name` attribute? Did the element have a name that conflicts with the html2pdf bundle?

Changing the scale did not solve the issue for me.
