### ISSUE TITLE
Print instead of save

### ISSUE THREAD

**Issue by scwong93** [eKoopmans/html2pdf.js#285]
Is there a way to open the pdf in the browser instead of downloading & manually opening it?

**Comment by scambier** [comment]
https://github.com/eKoopmans/html2pdf.js/issues/243 did the trick for me

**Comment by scwong93** [comment]
Thanks, I was able to resolve it in a similar fashion. 

html2pdf().set(opt).output('blob').then(blob => {
let iframe = document.createElement('iframe')
                iframe.src = `${URL.createObjectURL(blob)}`
                iframe.id = 'target-iframe'
                iframe.style.display = 'none'
}
document.getElementById('element').insertBefore(iframe, document.getElementById('element').childNodes[0]
document.getElementById('target-iframe').contentWindow.print()
