### ISSUE TITLE
 undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git

### ISSUE THREAD

**Issue by skills-surendra** [eKoopmans/html2pdf.js#286]
Hi i m getting the issue when i m installing this API:
i m getting error like : 
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.

**Comment by bmiller92** [comment]
Looks like this is an issue with  jspdf 1.5.3
https://github.com/MrRio/jsPDF/issues/2634
I installed 1.5.2 as a work around.

**Comment by colimba** [comment]
Hi, i've the same problem. It's there a solution for this? Is it planned to be mitigated? Or should i use v0.9.1?

**Comment by kishore075** [comment]
Hi,

I tried to install npm install --save html2pdf.js@1.5.2 too still same issue any updated

**Comment by oskarleonard** [comment]
We need to pin "jspdf": "1.5.2"  in html2pdf package json file

**Comment by kishore075** [comment]
Hi @oskarleonard  thanks that worked i cam install 1.4.1

**Comment by bianjp** [comment]
jsPDF just released [v2.0.0](https://github.com/MrRio/jsPDF/releases/tag/v2.0.0) which fixed the issue. I suggest html2pdf.js upgrade jsPDF to 2.0.0

**Comment by deshi9012** [comment]
Any update on this issue?

**Comment by xamthor** [comment]
would like for jsPDF to be updated to v2, trying to deploy this to a prod server and running into this issue

**Comment by eKoopmans** [comment]
😓 yes, I'm sorry this has been unresolved for so long.

For the time being this issue has been fixed in v0.9.3 by locking jsPDF to version 1.4.1. I will prioritise upgrading to jsPDF 2.x soon.
