### ISSUE TITLE
Can't save PDF to web server

### ISSUE THREAD

**Issue by Webjames-BE** [eKoopmans/html2pdf.js#306]
Hello,

I use this fantastic script to generate labels on a website and would like to save the result on the server instead of prompting the user to download it.

I can't find to way to achieve this, I tried many options but still don't now how to get from here:
html2pdf().set(opt).from(element).save();
to something that would save it on the server.

Thank you for your help !

Regards,

Greg

**Comment by Paytah232** [comment]
@Webjames-BE Did you solve this?
