### ISSUE TITLE
iOS generated PDF is completely blank

### ISSUE THREAD

**Issue by rsauchuck-gp** [eKoopmans/html2pdf.js#345]
The resulting document is 8 pages long (the desktop version produces a similar length file) but all the pages are blank except for the header and footer which I add with a function.

                var element = $('#recommendationsdisplay').html();
                var opt = {
                    margin: [.75,0,.75,0],
                    filename: 'Click_Start_' + Math.floor(Date.now() / 10000) + '.pdf',
                    enableLinks: true,
                    image: {
                        type: 'jpeg',
                        quality: 1
                    },
                    html2canvas: {
                        scale: 2,
                        dpi: 300,
                        letterRendering: true
                    },
                    jsPDF: {
                        unit: 'in',
                        format: 'letter',
                        orientation: 'portrait'
                    },
                    pagebreak:{
                        mode: ['avoid-all', 'css', 'legacy'],
                        avoid: 'div.recgrid-item'
                    }
                };

                html2pdf().from(element, 'string').set(opt).toPdf().get('pdf').then(function (pdfObject) {
                /* some image related encoding */
                    var headerTitle = "Recommendations";
                    var footerCR = "© 2020";

                    // Header and Footer
                    for (var i = 1; i < pdf_pages.length; i++) {
                        pdfObject.setPage(i);
                        pdfObject.setFontSize(14);
                        pdfObject.setTextColor('#0090DA');
                        pdfObject.addImage(headerData, 'PNG', 0, 0, 8.5, .5);
                        pdfObject.setFontSize(10);
                        pdfObject.setTextColor('#777777');
                        pdfObject.text(footerCR, 4, 10.5);
                        pdfObject.text(' ' + i, 7.375, 10.5);
                        pdfObject.addImage(logoData, 'PNG', .75, 10.25, 1, .325);
                    }

                }).save();

**Comment by rsauchuck-gp** [comment]
I managed to get the PDFs to load on iPhone and iPad by manipulating the CSS via JavaScript before calling html2pdf and then resetting them to the initial values afterword. Still I think there is some other issue as my document is less than 6 pages of content

**Comment by kabaehr** [comment]
Hey, I have a similar problem.
Could you explain a bit how you solved it by manipulating the CSS via JavaScript?

**Comment by rsauchuck-gp** [comment]
Hey there,
I found I had to specify a width and height for the missing content. Percentages didn’t work it had to be actual pixels. My content was dynamically generated so for every iteration, I added a multiple to the height of the missing div and saved both the initial “real” height and the “new” hard-coded height. Right before I called the html2pdf function, I set the div to the new size. When it was complete I reset it to the previous size. It happens so quickly you don’t see the change in the browser.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
