### ISSUE TITLE
S3 images are giving CORS in chrome and works with Mozilla

### ISSUE THREAD

**Issue by kishoreandra** [eKoopmans/html2pdf.js#368]
i have set the options as : 

var opt = {
                filename: 'test.pdf',
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: {
                    dpi: 300,
                    letterRendering: true,
                    useCORS: true,
                    allowTaint : false
                }
            };
I have set the crossOrigin attribute for image tags to "Anonymous"  and allowed all origins and headers for s3 bucket ,
This solved the CORS allow permit in mozilla whereas not in chrome (few images or not rendered and few does and this is not same behaviour it does change weirdly)

Though saw lots of issues and questions in stackoverflow none of them have worked to my luck 

Any suggestions are much appreciated ... Thank you

![image](https://user-images.githubusercontent.com/50901558/99665672-f5f38800-2a8f-11eb-9c9f-85930b17a44a.png)

**Comment by bckwcs** [comment]
@kishoreandra try adding crossOrigin="Anonymous" attribute to the img tag.

**Comment by konobukin** [comment]
Hi! How did you fixed it?

**Comment by kurkurzz** [comment]
@kishoreandra Did you manage to fix it? Appreciate if you could share your solution here.
