### ISSUE TITLE
Pseudo css not showing and pdf not starting from top of the pdf on safari (desktop/ios)

### ISSUE THREAD

**Issue by AndhikaR** [eKoopmans/html2pdf.js#388]
My setting currently like this 
                                {
				margin: 6,
				filename: this.recipe.title + '.pdf',
				image: { type: 'jpeg', quality: 1 },
				pagebreak: { mode: ['css', 'legacy'], avoid: '.page-breaker' },
				html2canvas: {
					scale: 1,
					proxy: 'http://localhost:3000',
					useCORS: true,
					allowTaint: true
				},
				jsPDF: {
					format: 'letter',
					orientation: 'portrait'
				}
			}

**Comment by VinzzB** [comment]
pdf not starting from top: I had the same issue and i solved this by adding scrollY: 0 to the html2canvas options.
Hope it helps!

**Comment by AndhikaR** [comment]
Thanks man, it works! appreciate it
