### ISSUE TITLE
Div does not prompt download

### ISSUE THREAD

**Issue by NicolasWent** [eKoopmans/html2pdf.js#399]
Hello,

I am trying to transform my div into a pdf.

I am using this simple code:

const element = document.getElementById("pdf-content");

html2pdf()
        .set({ html2canvas: { scale: 4 } })
        .from(element)
        .toPdf()
        .save("methodo.pdf");

But the download is not showing.

But if I do something like that:

`html2pdf("test");`

The download is prompted correctly.

I don't understand why it is not working on my project :(. I have tried to remove the style of "pdf-content", but still, it does not work

**Comment by mmoraes** [comment]
Try this instead:

```
const element = document.getElementById("pdf-content");

const opt = {
      filename: "name-your-file-here",
      image: { type: "jpeg", quality: 0.85 },
      html2canvas: {
        scale: 5,
        logging: true,
        letterRendering: true,
        useCORS: true,
      },
      jsPDF: {
        unit: "in",
        format: "letter",
        orientation: "portrait",
      },
    };

// Promise-based usage:
html2pdf()
  .set(opt)
  .from(element)
  .toPdf()
  .save();
```

**Comment by NicolasWent** [comment]
Hello,

Thank you very much for this fast answer, I have tried with your code copy and pasted, it still does not prompt download :'(

Here is my html: [https://code.litarvan.com/lukeluk.erb](https://code.litarvan.com/lukeluk.erb)
css: [https://code.litarvan.com/ineqebo.css](https://code.litarvan.com/ineqebo.css)
js: [https://code.litarvan.com/uxasuqe.coffeescript](https://code.litarvan.com/uxasuqe.coffeescript)

I don't understand why it does not prompt download for my div :'(

**Comment by mmoraes** [comment]
@NicolasWent A working example for you: https://jsfiddle.net/mateusmoraes/vh5jqow2/

_For demonstrations purposes I'm loading html2pdf via a bundled file: https://rawgit.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.min.js_

**Comment by NicolasWent** [comment]
Thank you very much for your time.

When I download the example you gave, the pdf file is empty :(

I also have tried to copy and paste your javascript into my project, I don't know why the download is still not showing (inside of the real project)

It does print in console the same things as inside of your example but the pdf is not created :(

**Comment by mmoraes** [comment]
@NicolasWent Ops, my bad... I wrongly set the margin there in the params ,so it may have triggered a silent error and therefore the PDF was not generated properly. Please take a look at the updated example: https://jsfiddle.net/mateusmoraes/vh5jqow2/

I've added some comments there, so you can have a better idea of what's going on and where :)

**Comment by NicolasWent** [comment]
Thank you very much this example is working :)

**Comment by mmoraes** [comment]
Awesome, glad to help 😉

**Comment by NicolasWent** [comment]
I understood why in my real code it was not working:

There is an issue with the lib because it does not prompt download on a local image. When I had img/image.png, the download was not prompting, but if I put a remote image, it is showing it

Thanks for your help anyway I learned a lot about the lib ^^
