### ISSUE TITLE
Unknown source type

### ISSUE THREAD

**Issue by jmriyaz84** [eKoopmans/html2pdf.js#402]
Hi , 
We are using html2pdf plugin in our VueJS project , but most of the time I am getting **"Unknown source type"** error
 **Code** 
const element = document.getElementById(elementName);
  const footerXAxis = orientationValue === "portrait" ? 150 : 250;
  const footerYAxis = orientationValue === "portrait" ? 290 : 200;
  const opt = {
    margin: [15, 10, 25, 10],
    filename: fileName,
    image: { type: "jpeg", quality: 1 },
    jsPDF: {
      unit: "mm",
      format: "a4",
      orientation: orientationValue
    }
  };
  html2pdf()
    .set(opt)
    .from(element)
    .toPdf()
    .get("pdf")
    .then(function(pdf) {
      let totalPages = pdf.internal.getNumberOfPages();
      pdf.setFontSize(11);
      for (let i = 1; i <= totalPages; i++) {
        pdf.text(header, 10, 10);
        pdf.setPage(i);
        pdf.text("Page " + i + " of " + totalPages, footerXAxis, footerYAxis);
      } 
    })
    .catch(e => {
      console.error("PDF Generation Error", e);
      Notify.create({
        color: "negative",
        position: "top",
        message: "Exception Occurs while generating PDF file",
        icon: "report_problem"
      });
    })
    .save();

**Error** 

PDF Generation Error Error: Unknown source type.
    at t.<anonymous> (vendor.ca495071.js:formatted:244814)
    at G (vendor.ca495071.js:formatted:244206)
    at K (vendor.ca495071.js:formatted:244219)
    at W (vendor.ca495071.js:formatted:244200)
    at MutationObserver.M (vendor.ca495071.js:formatted:244068)

<img width="323" alt="Unknown-source-issue" src="https://user-images.githubusercontent.com/8514576/109410757-ae499a00-79b6-11eb-8d47-2862c7c4e426.PNG">

**Comment by jmriyaz84** [comment]
Is got resolved

**Comment by VietBachDo** [comment]
Hey there,
@jmriyaz84 do you mind sharing how did it get resolved?

**Comment by jmriyaz84** [comment]
Coding issue , I was passing incorrect source type

**Comment by inigopanos** [comment]
Hey, I am just having this same problem. If anyone is still reading this or knows the answer, what do you mean exactly by passing an incorrect source type? I am trying to pass a <div id='container'> and it doesn't work, and I can't seem to find more information on this error so this is the only lead I've found.

**Comment by Zuhaib-700** [comment]
@inigopanos 

.from(element)= it must be going as null, in my case I was using useRef with initial value as null, so basiaclly it was sending null value all i had to do is set my ref in useEffect so it took the non null value
