### ISSUE TITLE
Issue in saving pdf from html

### ISSUE THREAD

**Issue by vasuneet** [eKoopmans/html2pdf.js#414]
Hi,

I am using the following command to save pdf :

var element = document.getElementById(this.props.data.receiptId);
        var opt = {
            margin: 1,
            filename: 'digitalReceipt.pdf',
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2 },
            jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
        };

        //var worker = html2pdf();
        // New Promise-based usage:
        html2pdf().set(opt).from(element).save();
![issue](https://user-images.githubusercontent.com/3884434/111542608-f3542700-873f-11eb-9391-dd701525b1b9.PNG)

**Comment by vasuneet** [comment]
I installed this module using the following command:

yarn add html2pdf.js

**Comment by ReenSalleh** [comment]
> I installed this module using the following command:
> 
> yarn add html2pdf-jspdf2 and i imported it in my react js component as below 👍
> import {html2pdf} from 'html2pdf-jspdf2';

@vasuneet , check this solution. [https://github.com/eKoopmans/html2pdf.js/issues/230#issuecomment-804022027](url)

**Comment by sagartmg** [comment]
in react you should do... import html2pdf from 'html2pdf.js'


and ....



 printPdf(){
        var doc = new jsPDF();   
        let printalbe_table =  document.getElementById('printdiv')
        
        if(printalbe_table){
            this.setState({
                pdf_mode_on:true
            },()=>{
                let date = new Date();
                var element = document.getElementById('printdiv');
                let time = `${date.getDate()}_${date.getMonth() + 1}_${date.getFullYear()}_${date.toLocaleTimeString().split(":")[0]}_${date.toLocaleTimeString().split(":")[1]}`;
                var opt = {
                margin:       [0.5,1,1,1],
                filename:     `inventory_report_${time}.pdf`,
                image:        { type: 'jpeg', quality: 0.98 },
                html2canvas:  { scale: 2 },
                jsPDF:        { unit: 'in', format: 'A4', orientation: 'portrait' }
                };
                
                // New Promise-based usage:
                html2pdf().from(element).set(opt).save().then((onFulfilled,onRejected)=>{
                    this.setState({
                        pdf_mode_on:false
                    })
                });
            })
        }
    }

**Comment by vasuneet** [comment]
thanks. I got this working.
