### ISSUE TITLE
blank space on top when page scrolled. 

### ISSUE THREAD

**Issue by sagartmg** [eKoopmans/html2pdf.js#420]
very top scrolled -> works file https://i.imgur.com/lg4gQym.png
little scrolled -> comes with blank space => https://i.imgur.com/mf4Rbct.png

**Comment by 7axiomsOfEuclid** [comment]
I experienced the same issue. 
I think @eKoopmans is no longer interested in working on this library.
Here is a quick tip for you. 
```
    window.scrollTo(0, 0);
    setTimeout(() => {
      // Export pdf here
    }, 300);
```

**Comment by sagartmg** [comment]
cool.. but if i were a user, i would be pissed off for the page being scrolled just for making pdfs.

**Comment by rajeshn95** [comment]
try giving `scrollY: 0` in your html2canvas option: `html2canvas: { scale: 1, scrollY: 0 }`, I hope this will resolve your issue.

**Comment by ruairidhflint** [comment]
> try giving `scrollY: 0` in your html2canvas option: `html2canvas: { scale: 1, scrollY: 0 }`, I hope this will resolve your issue.

Fantastic - just solved a bug me and the team have been wrestling with! Thank you.

**Comment by ruairidhflint** [comment]
Issue should be closed, `scrollY: 0` fixes the issue.

**Comment by sagartmg** [comment]
i was thinking of quitting programming just because i couldn't print a pdf property and neither did i found any other than this package for simply printing the dom element.....

Thanks for the developer team and  @rajeshn95

**Comment by ritikTandon** [comment]
> try giving `scrollY: 0` in your html2canvas option: `html2canvas: { scale: 1, scrollY: 0 }`, I hope this will resolve your issue.

You are a life saver <3

**Comment by Dacypher005** [comment]
Thanks for this...
