### ISSUE TITLE
No dist folder

### ISSUE THREAD

**Issue by WebStarLink** [eKoopmans/html2pdf.js#463]
Hello there! Dist folder is gone. URL get 404 error, and I see master branch hasn't dist folder.

**Comment by dellow88** [comment]
Having same issue using https://rawgit.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.min.js

**Comment by eKoopmans** [comment]
Working on it... this was a deliberate change, but I'll revert for now and release v10.0.1 soon.

I would like to remove the `dist` folder from git but will try to give more warning next time, and ensure that all use cases (CDNs/direct downloads) are still supported.

**Comment by Durgesh-Pratap** [comment]
> Working on it... this was a deliberate change, but I'll revert for now and release v10.0.1 soon.
> 
> I would like to remove the `dist` folder from git but will try to give more warning next time, and ensure that all use cases (CDNs/direct downloads) are still supported.

How much time it'll take ?
https://rawgit.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.min.js Still can't access

Folder still not found

**Comment by eKoopmans** [comment]
@Durgesh-Pratap it's reinstated now, rawgit may take a while to update its cache. In the meantime this (more correct) URL appears to have already updated:

https://rawgit.com/eKoopmans/html2pdf.js/master/dist/html2pdf.bundle.min.js

Please confirm and close if everything's working, thanks.
