### ISSUE TITLE
Low resolution PDFs generated with high resolution settings

### ISSUE THREAD

**Issue by devbret** [eKoopmans/html2pdf.js#478]
Hello @TukuToi and @eKoopmans, thank you for the excellent and practical html2pdf.js library. I am using the library to convert HTML pages, with a couple of images, into PDFs. At first, the PDFs were being generated in high resolution, but the page breaks were broken and content misaligned. After fixing the page break and alignment issues, now the PDFs being generated by the library are low resolution. Is there any insight(s) that you might be able to offer as to why the change in resolution occurred?

To help explain, below are the options and chained methods we are using to produce our PDFs:

![image](https://user-images.githubusercontent.com/73839896/133341355-acbe956e-a582-42f5-b32c-808c3fa649c6.png)

Are there settings that I'm not aware of that would enable for a higher resolution PDF being generated? Or is it possible that certain CSS settings might cause a fuzzy PDF?

Any assistance that you can provide is much appreciated. Thank you for your time.

**Comment by TukuToi** [comment]
Hi @devbret - just to clarify, I am not involved in creating this library, so the props go to @eKoopmans alone.

As for image quality, this is how I brought out the most of Images, but note, you will _always_ have a quality loss when printing:
```
var opt = {
    margin:       0.1,
    filename:     'my_file_name',
    image:        { type: 'png', quality: 1 },
    jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
};
html2pdf(contentToPrint, opt);
```

I used png since in general, PNG is a higher-quality compression format.

**Comment by devbret** [comment]
Hello @TukuToi, thank you for responding to my request for help. I went ahead and tried those options/settings, but there was no change in results. Are there any run environments wherein this library doesn't perform especially well? From what I understand about the html2pdf library, all of the processing (of the PDF) is done within the browser. Is this correct?

Beyond the advice you've already provided and the questions I've asked above, is there anything else you might be able to share with me that would help resolve this low resolution bug we're experiencing? 

Thank you for your time and the help you have provided. It is much appreciated.

**Comment by eKoopmans** [comment]
Hey @devbret the main way to get better quality (at the expense of file size) is to add the `scale` option to the html2canvas options, which will upscale the canvas by the specified ratio. For instance:

```js
html2pdf(contentToPrint, {
  html2canvas: { scale: 2 },
})
```

**Comment by devbret** [comment]
@eKoopmans Thank you for your quick response. Your suggestion worked perfectly, and the PDFs being generated are crisp and clear. Which is wonderful. 

Like you mentioned, file sizes did increase. Are there any other settings that you'd recommend I toy with in order to reduce the file size of the PDF output?

I appreciate your time.

**Comment by eKoopmans** [comment]
You can play with the scale value (e.g. 1.5), and you could try switching back to JPG if you were using the PNG suggestion, and see if you can find a sweet spot. Ultimately the PDFs generated by html2pdf.js are limited by the fact that it's capturing images - they'll never be as small or high quality as a "natively" rendered PDF.

On that note, my advice is always to favour a backend PDF tool like wkhtmltopdf if it fits your use case - html2pdf.js is specifically for projects that need to generate the PDF in the frontend.

**Comment by devbret** [comment]
We ended up using a value of 1.5 for the scale property. And then changed the image type to jpeg, which resulted in a file about 10% as large as when we were using the PNG value. That's awesome. Thank you for your help and for the tool itself.
