### ISSUE TITLE
Pdf text start from the middle of the page

### ISSUE THREAD

**Issue by isurunuwanthilaka** [eKoopmans/html2pdf.js#491]
When I convert html to pdf on chrome pdf start in the middle of the page and part from the end goes blank. Is there any help on this?

**Comment by mcabella** [comment]
Could you tell me how you managed to solve it? Thank you very much. I have the same problem.

**Comment by isurunuwanthilaka** [comment]
> Could you tell me how you managed to solve it? Thank you very much. I have the same problem.

I could not find any solution. So I had to abandon this package.

**Comment by mcabella** [comment]
oh, okey. Thanks
