### ISSUE TITLE
Existing Html Canvas isn't scaling/showing correctly

### ISSUE THREAD

**Issue by PLP-Casey** [eKoopmans/html2pdf.js#537]
So in our project we have an html web page that allows the user to upload a pdf using pdf.js which is shown on the page in a canvas. We want to be able to download the full page as a pdf, which works using html2pdf, except the canvas with the pdf doesn't scale for the new pdf and its also not centered so it gets cut off on one side. I've played around with the scale, width and windowWidth options on html2canvas in the html2pdf call, but none of them affected the canvas. Any ideas or suggestions would be great.

**Comment by PLP-Casey** [comment]
I found a way to change the attribute size of the canvas which fixed that issue

**Comment by RegueraDaniel** [comment]
> I found a way to change the attribute size of the canvas which fixed that issue

Can you share those changes or the code that works?

Thank you for your library!
