### ISSUE TITLE
Blank page on Ios or Android device when generating PDF

### ISSUE THREAD

**Issue by yavorhr** [eKoopmans/html2pdf.js#542]
Hello,

I have issue when I try to generate PDF with IOS or Android device. I got then completely blank page. It works great on PC though.
Below is my code : 

 function generateResume() {
    let opt = {
        margin: 0,
        filename: 'fileName',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
            scale: 4,
            letterRendering: true,
        },
        jsPDF: { format: 'a4', orientation: 'portrait' },
        pagebreak: {
            // mode: "avoid-all",
            // mode: ["avoid-all", "css", "legacy"],
            // before: ".pageInPDF",
            // after: ".stepInPDF",
        }
    };
    html2pdf().set(opt).from(areaCv).save();
}

I will be glad if anyone is able to help. I tried the rest of the suggestions from the other issues, but didn't work for me.

**Comment by AliAlmuhaysin** [comment]
Hello @yavorhr , Did you solve the issue? if yes can you share it please?
