### ISSUE TITLE
Is there a way to use jsPDF setProperties  ?

### ISSUE THREAD

**Issue by yertech** [eKoopmans/html2pdf.js#564]
Hi,

I would like to add metadatas or properties to my pdf before saving, but I didn't find a way to access to the jsPDF-instance before saving and use setDocumentProperties or setProperties

**Comment by vtzk** [comment]
It might be too late for a response, but I recently encountered a similar issue and discovered a straightforward, albeit somewhat unconventional, solution.

Please note, this approach is somewhat unorthodox and may not be future-proof, as it could potentially conflict with future updates to the library. 🤷

```js
// Create a new instance of the html2pdf worker
const worker2 = new html2pdf.Worker;

// Configure the worker with options and the target element
worker.set(opt).from(element);

// This will do make the `prop.pdf` available
worker.toPdf();

// Set custom document properties for the generated PDF
worker.prop.pdf.setDocumentProperties({ 
    author: 'YOUR_NAME', 
    keywords: "keyword_1, keyword_2", 
    creator: 'YOUR_NAME',
    subject: 'YOUR_SUBJECT'
});

```
This method enables direct access to the jsPDF instance through worker.prop.pdf, allowing you to use its various functionalities such as [setDocumentProperties](https://artskydj.github.io/jsPDF/docs/jsPDF.html#setDocumentProperties)
