### ISSUE TITLE
Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot' when use html2pdf

### ISSUE THREAD

**Issue by BasemMahmoud** [eKoopmans/html2pdf.js#629]
browserLink:67 Uncaught DOMException: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Sharing constructed stylesheets in multiple documents is not allowed

**Comment by BasemMahmoud** [comment]
Done

**Comment by beratbayram** [comment]
How did you solve it?
