### ISSUE TITLE
html2pdf.js return blank page result when content large

### ISSUE THREAD

**Issue by DarkHorseCorder** [eKoopmans/html2pdf.js#639]
I'm using html2pdf to generate report
When report have about 60pages, it works well.
But if I select more reports about 100pages, it return empty, blank page.
I set async option as true and increased timeout. 
But it's not solution.
How can I fix this problem?

**Comment by tmislos-cgi** [comment]
you are probably hitting the htmlcanvas height limit. If it is, you can try the way I did it. You can look at my answer here: https://github.com/eKoopmans/html2pdf.js/issues/19#issuecomment-1337037147

**Comment by davidnbooth** [comment]
[html3pdf](https://www.npmjs.com/package/html3pdf) solves this by rendering each page on its own canvas, although this is much slower.
